# Generated by Django 5.2.8 on 2025-11-21 21:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(unique=True, verbose_name='Orden')),
                ('low_risk_min', models.IntegerField(verbose_name='Riesgo Bajo - Mínimo')),
                ('low_risk_max', models.IntegerField(verbose_name='Riesgo Bajo - Máximo')),
                ('medium_risk_min', models.IntegerField(verbose_name='Riesgo Medio - Mínimo')),
                ('medium_risk_max', models.IntegerField(verbose_name='Riesgo Medio - Máximo')),
                ('high_risk_min', models.IntegerField(verbose_name='Riesgo Alto - Mínimo')),
                ('high_risk_max', models.IntegerField(verbose_name='Riesgo Alto - Máximo')),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('SUPERUSER', 'Superuser'), ('COMPANY_ADMIN', 'Company Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'COMPANY_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('identification', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('ethnicity', models.CharField(choices=[('MESTIZO', 'Mestizo'), ('INDIGENA', 'Indígena'), ('AFROECUATORIANO', 'Afroecuatoriano'), ('BLANCO', 'Blanco'), ('MONTUBIO', 'Montubio'), ('OTRO', 'Otro')], max_length=20, verbose_name='Auto-identificación étnica')),
                ('area', models.CharField(max_length=100, verbose_name='Área de trabajo')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('education_level', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Técnico'), ('UNIVERSITARIO', 'Universitario'), ('POSTGRADO', 'Postgrado')], max_length=20, verbose_name='Nivel de instrucción')),
                ('years_of_experience', models.IntegerField(verbose_name='Años de experiencia en la empresa')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='infrastructure.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('COMPLETED', 'Completada')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('date_started', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='infrastructure.employee')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-date_started'],
                'unique_together': {('employee', 'year', 'status')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Número de ítem')),
                ('text', models.TextField(verbose_name='Texto de la pregunta')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='infrastructure.dimension')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(choices=[(1, 'En desacuerdo'), (2, 'Poco de acuerdo'), (3, 'Parcialmente de acuerdo'), (4, 'Completamente de acuerdo')], verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='infrastructure.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='infrastructure.question')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'unique_together': {('evaluation', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RiskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Puntaje')),
                ('risk_level', models.CharField(choices=[('BAJO', 'Riesgo Bajo'), ('MEDIO', 'Riesgo Medio'), ('ALTO', 'Riesgo Alto')], max_length=10, verbose_name='Nivel de riesgo')),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_results', to='infrastructure.dimension')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_results', to='infrastructure.evaluation')),
            ],
            options={
                'verbose_name': 'Resultado de Riesgo',
                'verbose_name_plural': 'Resultados de Riesgo',
                'unique_together': {('evaluation', 'dimension')},
            },
        ),
    ]
