# Generated by Django 5.2.8 on 2025-11-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explicación detallada con ejemplos para ayudar a entender la pregunta', verbose_name='Explicación de la pregunta'),
        ),
    ]
