# Generated by Django 5.2.8 on 2025-11-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0003_evaluation_age_range_evaluation_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stored_password",
            field=models.CharField(
                blank=True,
                help_text="Contraseña almacenada para referencia del administrador",
                max_length=255,
                null=True,
                verbose_name="Contraseña almacenada",
            ),
        ),
    ]
