# Generated by Django 5.2.8 on 2025-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0004_customuser_stored_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="years_of_experience",
        ),
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(
                default="2020-01-01",
                help_text="La antigüedad se calculará automáticamente desde esta fecha",
                verbose_name="Fecha de ingreso a la empresa",
            ),
        ),
    ]
