# Generated by Django 5.2.8 on 2025-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0005_remove_employee_years_of_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="work_area_erp",
            field=models.CharField(
                choices=[
                    ("ADMINISTRATIVA", "Administrativa"),
                    ("OPERATIVA", "Operativa"),
                    ("COMERCIAL", "Comercial"),
                    ("LOGISTICA", "Logística"),
                    ("PRODUCCION", "Producción"),
                    ("TRANSFORMACION", "Transformación"),
                    ("SOPORTE", "Soporte"),
                    ("TECNOLOGIA_INNOVACION", "Tecnología e Innovación"),
                ],
                default="ADMINISTRATIVA",
                help_text="Área según clasificación del cuestionario MDT (para comparación con evaluaciones)",
                max_length=30,
                verbose_name="Área de Trabajo ERP",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="area",
            field=models.CharField(
                help_text="Nombre del área según la empresa",
                max_length=100,
                verbose_name="Área de trabajo (Texto libre)",
            ),
        ),
    ]
