"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Configurar PyMySQL como driver de MySQL (más fácil en Windows)
try:
    import pymysql
    pymysql.install_as_MySQLdb()
except ImportError:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def get_env_variable(var_name, default=None):
    """Obtiene una variable de entorno o lanza error si no existe"""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Usar variable de entorno en producción
SECRET_KEY = get_env_variable(
    'DJANGO_SECRET_KEY',
    default='django-insecure-zocux(x8om@@%82buv&_(x_@-ar%_qox-cifg)8#f**e@_+p+7'  # Solo para desarrollo
)

# SECURITY WARNING: don't run with debug turned on in production!
# Usar variable de entorno en producción
DEBUG = get_env_variable('DJANGO_DEBUG', default='True').lower() == 'true'

# Hosts permitidos - CRÍTICO para seguridad
ALLOWED_HOSTS = get_env_variable('DJANGO_ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Configuración de seguridad (solo en producción)
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Strict'
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Strict'
    
    # Configurar CSRF_TRUSTED_ORIGINS desde variable de entorno
    csrf_origins = get_env_variable('DJANGO_CSRF_TRUSTED_ORIGINS', default='')
    if csrf_origins:
        CSRF_TRUSTED_ORIGINS = csrf_origins.split(',')
else:
    # En desarrollo, permitir localhost
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'django_browser_reload',
    'apps.infrastructure',
    'apps.presentation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'apps' / 'presentation' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Cargar configuración adicional de producción si DEBUG=False
if not DEBUG:
    try:
        from .settings_production import *
    except ImportError:
        pass

# Detectar entorno y configurar base de datos apropiada
# PythonAnywhere establece USER automáticamente
# También podemos detectar por el hostname o variable de entorno
is_pythonanywhere = (
    'pythonanywhere.com' in os.environ.get('HOSTNAME', '') or
    'PYTHONANYWHERE_DOMAIN' in os.environ or
    os.environ.get('USER', '').endswith('pythonanywhere') or
    '/home/' in os.environ.get('HOME', '') and 'pythonanywhere' in os.environ.get('HOME', '')
)

if is_pythonanywhere:
    # Configuración para PythonAnywhere (producción)
    PA_USERNAME = os.environ.get('USER', '')
    # Limpiar si termina en 'pythonanywhere'
    if PA_USERNAME.endswith('pythonanywhere'):
        PA_USERNAME = PA_USERNAME.replace('pythonanywhere', '')
    
    # Cargar configuración específica de PythonAnywhere
    try:
        from .settings_pythonanywhere import *
    except ImportError:
        pass
    
    # Si no se cargó desde settings_pythonanywhere, configurar aquí
    if 'DATABASES' not in locals() or not DATABASES.get('default'):
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': get_env_variable('DB_NAME', default=f'{PA_USERNAME}$default'),
                'USER': get_env_variable('DB_USER', default=PA_USERNAME),
                'PASSWORD': get_env_variable('DB_PASSWORD', default=''),
                'HOST': get_env_variable('DB_HOST', default=f'{PA_USERNAME}.mysql.pythonanywhere-services.com'),
                'PORT': get_env_variable('DB_PORT', default='3306'),
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4',
                },
            }
        }
elif get_env_variable('USE_SQLITE', default='False').lower() == 'true':
    # Configuración para desarrollo local con SQLite (opcional)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif get_env_variable('USE_MYSQL_LOCAL', default='True').lower() == 'true':
    # Configuración para desarrollo local con MySQL/MariaDB (XAMPP)
    # Workaround para MariaDB 10.4 (XAMPP) - Django requiere 10.5+ pero funciona con 10.4
    import django.db.backends.mysql.base
    import django.db.backends.mysql.features
    
    # Deshabilitar verificación de versión
    def patched_check_database_version_supported(self):
        """Deshabilitar verificación de versión para desarrollo local con MariaDB 10.4"""
        pass
    
    # Deshabilitar RETURNING (no soportado en MariaDB 10.4)
    def patched_can_return_columns_from_insert(self):
        """Deshabilitar RETURNING para MariaDB 10.4"""
        return False
    
    django.db.backends.mysql.base.DatabaseWrapper.check_database_version_supported = patched_check_database_version_supported
    django.db.backends.mysql.features.DatabaseFeatures.can_return_columns_from_insert = property(lambda self: False)
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': get_env_variable('DB_NAME', default='mdt_erp_dev'),
            'USER': get_env_variable('DB_USER', default='root'),
            'PASSWORD': get_env_variable('DB_PASSWORD', default=''),
            'HOST': get_env_variable('DB_HOST', default='127.0.0.1'),
            'PORT': get_env_variable('DB_PORT', default='3306'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'charset': 'utf8mb4',
            },
        }
    }
else:
    # Configuración por defecto para desarrollo local (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Mínimo 12 caracteres para mayor seguridad
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'theme' / 'static',
]

# PWA Configuration
PWA_APP_NAME = 'Sistema de Evaluación Psicosocial'
PWA_APP_DESCRIPTION = 'Sistema de evaluación de riesgo psicosocial para empresas'
PWA_APP_THEME_COLOR = '#1e40af'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_START_URL = '/'
PWA_APP_SCOPE = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'infrastructure.CustomUser'

# Authentication URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'  # Se redirige según el rol del usuario en las vistas
LOGOUT_REDIRECT_URL = '/login/'

TAILWIND_APP_NAME = 'theme'

NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'

INTERNAL_IPS = [
    "127.0.0.1",
]
